Repository GoormOnlyOne/OnlyOne-Front, pull requests merged in 2025-08, with the labels that each got.

#64 [feat] 모임 / 정기 모임 / 거래 목록 페이지 API 연결
  package-lock.json
  package.json
  src/api/upload.ts
  src/components/common/Toast/ToastProvider.ts
  src/components/domain/category/CategorySection.tsx
  src/components/domain/meeting/MeetingForm.tsx
  src/components/domain/meeting/ScheduleForm.tsx
  src/components/domain/meeting/ScheduleList.tsx
  src/components/layout/title/Layout.tsx
  src/pages/Meeting/MeetingCreate.tsx
  src/pages/Meeting/MeetingEdit.tsx
  src/pages/Meeting/MeetingHome.tsx
  src/pages/Meeting/MeetingScheduleCrate.tsx
  src/pages/Meeting/MeetingScheduleCreate.tsx
  src/pages/Meeting/MeetingScheduleEdit.tsx
  src/pages/Meeting/ParticipationStatus.tsx
  src/pages/Mypage/WalletHistory.tsx
  src/pages/Payment/PointCharge.tsx
  src/routes/Router.tsx
Labels: 내모임, 마이페이지

#72 [feat] 피드 상세 페이지 구현
  src/api/client.ts
  src/components/common/Modal.tsx
  src/components/domain/meeting/CreateMeetingCard.tsx
  src/components/domain/meeting/MeetingFeedForm.tsx
  src/components/domain/meeting/MeetingFeedGrid.tsx
  src/components/domain/meeting/MeetingForm.tsx
  src/components/domain/meeting/ScheduleList.tsx
  src/pages/Meeting/MeetingEdit.tsx
  src/pages/Meeting/MeetingFeedCreate.tsx
  src/pages/Meeting/MeetingFeedDetail.tsx
  src/pages/Meeting/MeetingFeedEdit.tsx
  src/pages/Meeting/ParticipationStatus.tsx
Labels: 내모임

#73 [feat] 알림 api 연결
  src/api/client.ts
  src/api/notification.ts
  src/pages/Notice.tsx
  src/types/notification.ts
Labels: 알림

#104 [style] 버튼 색상 변경 및 알림 페이지 구현
  package-lock.json
  package.json
  src/api/notification.ts
  src/components/common/ListCard.tsx
  src/components/common/SortChips.tsx
  src/components/domain/meeting/MeetingFeedForm.tsx
  src/components/domain/meeting/MeetingForm.tsx
  src/components/domain/notification/NotificationItem.tsx
  src/components/domain/signup/Step3.tsx
  src/pages/Chat/ChatRoomList.tsx
  src/pages/Mypage/Mypage.tsx
  src/pages/Mypage/Profile.tsx
  src/pages/Mypage/Wallet.tsx
  src/pages/Mypage/WalletHistory.tsx
  src/pages/Notice.tsx
  src/pages/Signup.tsx
Labels: 알림

#114 [refactor] 내 모임 보기 페이지 추가 / 스타일 수정 / 정산, 결제 관련 변경사항 반영
  src/components/common/ListCard.tsx
  src/components/common/Modal.tsx
  src/components/common/SortChips.tsx
  src/components/common/TabBar.tsx
  src/components/domain/meeting/MeetingList.tsx
  src/components/domain/meeting/SettlementCard.tsx
  src/components/layout/title/Layout.tsx
  src/pages/Feed/FeedList.tsx
  src/pages/Meeting/MyMeeting.tsx
  src/pages/Mypage/MySettlement.tsx
  src/pages/Mypage/WalletHistory.tsx
  src/pages/Payment/Success.tsx
  src/routes/Router.tsx
Labels: 내모임, 마이페이지
